# Generated by Django 4.2.7 on 2026-02-04 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food & Beverages'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('books', 'Books & Media'), ('other', 'Other')], default='other', help_text='Product category', max_length=50)),
                ('current_stock', models.IntegerField(default=0, help_text='Current quantity in stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('safety_stock', models.IntegerField(default=10, help_text='Minimum stock level to maintain (buffer)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of sales')),
                ('quantity_sold', models.IntegerField(help_text='Number of units sold', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('product', models.ForeignKey(help_text='Product sold', on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Sales Data',
                'verbose_name_plural': 'Sales Data',
                'ordering': ['-date', 'product'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['product', 'date'], name='inventory_s_product_96b5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['date'], name='inventory_s_date_5663ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesdata',
            unique_together={('product', 'date')},
        ),
    ]
