# Generated by Django 6.0.2 on 2026-02-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Name of the driver', max_length=100)),
                ('trip_date', models.DateField(help_text='Date of the trip')),
                ('average_speed', models.FloatField(help_text='Average speed during trip (km/h)')),
                ('max_speed', models.FloatField(help_text='Maximum speed reached (km/h)')),
                ('harsh_braking_events', models.IntegerField(default=0, help_text='Number of harsh braking incidents')),
                ('rapid_acceleration_events', models.IntegerField(default=0, help_text='Number of rapid acceleration incidents')),
                ('cornering_speed', models.FloatField(default=0, help_text='Average cornering speed (km/h)')),
                ('risk_score', models.FloatField(blank=True, help_text='Calculated risk score (0-100)', null=True)),
                ('behavior_class', models.CharField(blank=True, choices=[('Safe', 'Safe'), ('Moderate', 'Moderate'), ('Risky', 'Risky')], help_text='AI classified behavior category', max_length=20, null=True)),
                ('recommendations', models.TextField(blank=True, help_text='AI generated safety recommendations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Data',
                'verbose_name_plural': 'Driver Data Records',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
    ]
