# Generated by Django 5.0.1 on 2026-02-14 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('UPSC', 'Union Public Service Commission'), ('SSC', 'Staff Selection Commission'), ('BANKING', 'Banking Exams'), ('RAILWAYS', 'Indian Railways'), ('STATE_PSC', 'State Public Service Commission'), ('DEFENCE', 'Defence Services')], default='STATE_PSC', max_length=20)),
                ('official_link', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Detailed eligibility requirements', null=True)),
                ('age_limit_min', models.IntegerField(help_text='Minimum age limit in years', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(60)])),
                ('age_limit_max', models.IntegerField(help_text='Maximum age limit in years', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(65)])),
                ('educational_qualification', models.CharField(help_text='Required educational qualification (e.g., 10th, 12th, Graduate)', max_length=255)),
                ('syllabus_text', models.TextField(blank=True, help_text='Exam syllabus in detail', null=True)),
                ('application_start_date', models.DateField(help_text='Application form start date')),
                ('application_end_date', models.DateField(help_text='Application form end date')),
                ('exam_date', models.DateField(help_text='Scheduled examination date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Exam',
                'verbose_name_plural': 'Government Exams',
                'ordering': ['-application_start_date'],
            },
        ),
    ]
