# Generated by Django 5.0.1 on 2026-02-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for category (e.g., UPSC, SSC)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-mortarboard)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Category',
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('UPSC', 'Union Public Service Commission'), ('SSC', 'Staff Selection Commission'), ('BANKING', 'Banking Exams'), ('RAILWAYS', 'Indian Railways'), ('STATE_PSC', 'State Public Service Commission'), ('DEFENCE', 'Defence Services')], default='STATE_PSC', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Dynamic exam category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examcategory'),
        ),
    ]
