# Generated by Django 5.0.1 on 2026-02-14 10:50

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default exam categories from EXAM_TYPES"""
    ExamCategory = apps.get_model('exams', 'ExamCategory')

    categories_data = [
        {'name': 'Union Public Service Commission', 'code': 'UPSC', 'icon_class': 'bi-mortarboard'},
        {'name': 'Staff Selection Commission', 'code': 'SSC', 'icon_class': 'bi-briefcase'},
        {'name': 'Banking Exams', 'code': 'BANKING', 'icon_class': 'bi-bank'},
        {'name': 'Indian Railways', 'code': 'RAILWAYS', 'icon_class': 'bi-train'},
        {'name': 'State Public Service Commission', 'code': 'STATE_PSC', 'icon_class': 'bi-building'},
        {'name': 'Defence Services', 'code': 'DEFENCE', 'icon_class': 'bi-shield'},
    ]

    for cat_data in categories_data:
        ExamCategory.objects.get_or_create(
            code=cat_data['code'],
            defaults={
                'name': cat_data['name'],
                'icon_class': cat_data['icon_class'],
                'is_active': True
            }
        )


def link_exams_to_categories(apps, schema_editor):
    """Link existing exams to categories based on exam_type"""
    Exam = apps.get_model('exams', 'Exam')
    ExamCategory = apps.get_model('exams', 'ExamCategory')

    for exam in Exam.objects.filter(category__isnull=True):
        try:
            category = ExamCategory.objects.get(code=exam.exam_type)
            exam.category = category
            exam.save(update_fields=['category'])
        except ExamCategory.DoesNotExist:
            # Log warning but don't fail if category doesn't exist
            print(f"Warning: No category found for exam type '{exam.exam_type}'")


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examcategory_alter_exam_exam_type_exam_category'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
        migrations.RunPython(link_exams_to_categories),
    ]
