# Generated by Django 5.2 on 2026-01-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=255, unique=True)),
                ('block_type', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer'), ('SIDEBAR', 'Sidebar'), ('BANNER', 'Banner'), ('PROMO', 'Promo'), ('WIDGET', 'Widget'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('content', models.TextField()),
                ('css_classes', models.CharField(blank=True, max_length=255)),
                ('custom_css', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_on', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Global Blocks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('PAGE', 'Page Template'), ('HOME', 'Home Page'), ('BLOG', 'Blog Post'), ('PRODUCT', 'Product Page'), ('CATEGORY', 'Category Page'), ('LANDING', 'Landing Page'), ('CUSTOM', 'Custom')], default='PAGE', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_content', models.TextField(blank=True)),
                ('allowed_block_types', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('max_blocks', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_classes', models.CharField(blank=True, max_length=255)),
                ('custom_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='templates_app.template')),
            ],
            options={
                'verbose_name_plural': 'Template Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('variable_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('COLOR', 'Color'), ('URL', 'URL'), ('IMAGE', 'Image'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select')], default='TEXT', max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='templates_app.template')),
            ],
            options={
                'verbose_name_plural': 'Template Variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('accent_color', models.CharField(default='#28a745', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('font_family', models.CharField(default='sans-serif', max_length=100)),
                ('font_size_base', models.PositiveIntegerField(default=16)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
