# Generated by Django 5.2 on 2026-01-24 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_education_notification_skill_workexperience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('technical', 'Technical Question'), ('behavioral', 'Behavioral Question'), ('situational', 'Situational Question'), ('experience', 'Experience-Based Question')], default='technical', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('question', models.TextField()),
                ('expected_keywords', models.JSONField(default=list, help_text='List of keywords expected in the answer')),
                ('sample_answer', models.TextField(blank=True, help_text='Sample ideal answer for reference')),
                ('max_score', models.IntegerField(default=10, help_text='Maximum score for this question')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='jobs.jobcategory')),
                ('skills_tested', models.ManyToManyField(blank=True, related_name='interview_questions', to='jobs.skill')),
            ],
            options={
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['category', 'difficulty', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('total_score', models.IntegerField(default=0, help_text='Total interview score out of 100')),
                ('max_score', models.IntegerField(default=100, help_text='Maximum possible score')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=30, help_text='Time limit for the interview')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-started_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=10)),
                ('feedback', models.TextField(blank=True, help_text='AI-generated feedback on the response')),
                ('keywords_found', models.JSONField(default=list, help_text='Keywords found in the answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.interviewquestion')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.interviewsession')),
            ],
            options={
                'verbose_name_plural': 'Interview Responses',
                'ordering': ['interview_session', 'created_at'],
                'unique_together': {('interview_session', 'question')},
            },
        ),
    ]
