# Generated by Django 5.2 on 2026-01-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_interviewquestion_interviewsession_interviewresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='List of choices for MCQ (e.g., ["A", "B", "C", "D"])'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Correct answer for MCQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('technical', 'Technical Question'), ('behavioral', 'Behavioral Question'), ('situational', 'Situational Question'), ('experience', 'Experience-Based Question'), ('mcq', 'Multiple Choice Question')], default='technical', max_length=20),
        ),
    ]
