# Generated by Django 5.0.1 on 2026-02-06 11:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Spending Pattern'), ('alert', 'Budget Alert'), ('recommendation', 'Savings Recommendation'), ('forecast', 'Spending Forecast')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial Insight',
                'verbose_name_plural': 'Financial Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10)),
                ('category', models.CharField(choices=[('Food', 'Food & Dining'), ('Transport', 'Transportation'), ('Utilities', 'Utilities & Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health & Wellness'), ('Salary', 'Salary & Income'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food & Dining'), ('Transport', 'Transportation'), ('Utilities', 'Utilities & Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health & Wellness'), ('Salary', 'Salary & Income'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Other', 'Other')], max_length=20, unique=True)),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('month', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['year', 'month', 'category'],
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
