# Generated by Django 5.2 on 2026-02-06 07:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('trend', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Sideways', 'Sideways'), ('Volatile', 'Volatile')], max_length=20)),
                ('key_findings', models.JSONField(default=list)),
                ('recommendation', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional report data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reports', to='market_analysis.stock')),
            ],
            options={
                'verbose_name_plural': 'Market Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(db_index=True)),
                ('target_date', models.DateField(db_index=True)),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('model_type', models.CharField(choices=[('LinearRegression', 'Linear Regression'), ('RandomForest', 'Random Forest'), ('LSTM', 'LSTM Neural Network'), ('XGBoost', 'XGBoost')], default='LinearRegression', max_length=50)),
                ('mse', models.FloatField(blank=True, help_text='Mean Squared Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R-squared Score', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, choices=[('BUY', 'Buy Signal'), ('SELL', 'Sell Signal'), ('HOLD', 'Hold Signal')], max_length=10)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence level in percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='market_analysis.stock')),
            ],
            options={
                'verbose_name_plural': 'Predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['stock', 'prediction_date'], name='market_anal_stock_i_096924_idx')],
                'unique_together': {('stock', 'prediction_date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('close', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('moving_average_5', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('moving_average_10', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('moving_average_20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('moving_average_50', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='market_analysis.stock')),
            ],
            options={
                'verbose_name_plural': 'Historical Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='market_anal_stock_i_f6b475_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VolatilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(db_index=True)),
                ('daily_volatility', models.FloatField(help_text='Standard deviation of daily returns')),
                ('annualized_volatility', models.FloatField(help_text='Annualized volatility (252 trading days)')),
                ('var_95', models.FloatField(blank=True, help_text='Value at Risk at 95% confidence level', null=True)),
                ('var_99', models.FloatField(blank=True, help_text='Value at Risk at 99% confidence level', null=True)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk'), ('Very High', 'Very High Risk')], max_length=20)),
                ('period_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volatility_analyses', to='market_analysis.stock')),
            ],
            options={
                'verbose_name_plural': 'Volatility Analyses',
                'ordering': ['-analysis_date'],
                'unique_together': {('stock', 'analysis_date')},
            },
        ),
    ]
