# Generated by Django 5.0.1 on 2026-02-10 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('role', models.CharField(max_length=100, verbose_name='Role/Position')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('performance_category', models.CharField(choices=[('high_potential', 'High Potential'), ('needs_training', 'Needs Training'), ('stable', 'Stable'), ('promotion_candidate', 'Promotion Candidate')], default='stable', max_length=50, verbose_name='Performance Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Record Date')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='Tasks Completed')),
                ('efficiency', models.FloatField(default=5.0, help_text='Rate efficiency from 1 (poor) to 10 (excellent)', verbose_name='Efficiency Score (1-10)')),
                ('quality', models.FloatField(default=5.0, help_text='Rate quality from 1 (poor) to 10 (excellent)', verbose_name='Quality Rating (1-10)')),
                ('hours_worked', models.FloatField(default=8.0, verbose_name='Hours Worked')),
                ('manager_notes', models.TextField(blank=True, help_text='Additional comments or observations', null=True, verbose_name='Manager Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performancerecord_set', to='performance.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Performance Record',
                'verbose_name_plural': 'Performance Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='performance_employe_52e283_idx')],
            },
        ),
    ]
