# Generated by Django 5.0.1 on 2026-02-10 10:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price_per_ton', models.FloatField(help_text='Price per ton of carbon credit in USD', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Carbon Prices',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('industry_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('energy', 'Energy & Power'), ('chemical', 'Chemical'), ('cement', 'Cement'), ('steel', 'Steel & Iron'), ('textile', 'Textile'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=50)),
                ('emission_limit', models.FloatField(help_text='Annual carbon emission limit in tons CO2', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_emission', models.FloatField(help_text='Predicted emission in tons CO2')),
                ('prediction_month', models.IntegerField()),
                ('prediction_year', models.IntegerField()),
                ('trading_suggestion', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence score (0-1)', null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='tracker.industry')),
            ],
            options={
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('emission_amount', models.FloatField(help_text='Emission amount in tons CO2', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tracker.industry')),
            ],
            options={
                'verbose_name_plural': 'Emission Records',
                'ordering': ['-year', '-month'],
                'unique_together': {('industry', 'year', 'month')},
            },
        ),
    ]
