# Generated by Django 5.0.1 on 2026-02-13 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the location', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or region', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country name', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9)),
                ('location_type', models.CharField(choices=[('city', 'City'), ('landmark', 'Landmark'), ('address', 'Address'), ('airport', 'Airport'), ('station', 'Station')], default='city', help_text='Type of location', max_length=20)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular destination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_locati_name_65ac84_idx'), models.Index(fields=['city', 'state'], name='core_locati_city_ef2718_idx'), models.Index(fields=['latitude', 'longitude'], name='core_locati_latitud_367ccc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('estimated_time_mins', models.FloatField()),
                ('traffic_factor', models.FloatField(default=1.0)),
                ('fuel_cost', models.FloatField(blank=True, null=True)),
                ('route_type', models.CharField(choices=[('fastest', 'Fastest'), ('shortest', 'Shortest'), ('scenic', 'Scenic'), ('eco', 'Eco-Friendly')], max_length=50)),
                ('coordinates', models.JSONField(help_text='Route coordinates as JSON array of [lat, lng] pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_suggestions_to', to='core.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_suggestions_from', to='core.location')),
            ],
            options={
                'verbose_name_plural': 'Route Suggestions',
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True, unique=True)),
                ('preferred_transport_mode', models.CharField(choices=[('car', 'Car'), ('bike', 'Motorcycle'), ('bus', 'Bus'), ('train', 'Train'), ('walking', 'Walking')], default='car', help_text='Default transport mode', max_length=20)),
                ('route_priority', models.CharField(choices=[('time', 'Fastest Route'), ('distance', 'Shortest Distance'), ('cost', 'Lowest Cost'), ('scenic', 'Scenic Route'), ('eco', 'Eco-Friendly')], default='time', help_text='What user prioritizes in routes', max_length=20)),
                ('avoid_tolls', models.BooleanField(default=False, help_text='Prefer toll-free routes')),
                ('avoid_highways', models.BooleanField(default=False, help_text='Avoid highways')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable traffic notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_home_location', models.ForeignKey(blank=True, help_text="User's home location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_home', to='core.location')),
                ('default_work_location', models.ForeignKey(blank=True, help_text="User's work location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_work', to='core.location')),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('traffic_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate-Low'), (4, 'Moderate'), (5, 'Moderate-High'), (6, 'High'), (7, 'Very High'), (8, 'Severe'), (9, 'Extreme'), (10, 'Gridlock')], default=4, help_text='Traffic congestion level (1-10)')),
                ('travel_time', models.FloatField(help_text='Actual travel time in minutes')),
                ('weather_condition', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('heavy_rain', 'Heavy Rain'), ('snow', 'Snow'), ('fog', 'Fog'), ('storm', 'Storm')], default='clear', help_text='Weather during travel', max_length=20)),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('bike', 'Motorcycle'), ('bus', 'Bus'), ('train', 'Train'), ('walking', 'Walking')], default='car', help_text='Mode of transport used', max_length=20)),
                ('route_type', models.CharField(help_text='Type of route taken (fastest, shortest, scenic)', max_length=50)),
                ('fuel_cost', models.FloatField(blank=True, help_text='Estimated fuel cost in local currency', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this trip record was created')),
                ('date_of_travel', models.DateTimeField(help_text='Actual date and time of travel')),
                ('destination', models.ForeignKey(help_text='Destination location', on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='core.location')),
                ('source', models.ForeignKey(help_text='Starting location', on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='core.location')),
            ],
            options={
                'verbose_name_plural': 'Trip Histories',
                'ordering': ['-date_of_travel'],
                'indexes': [models.Index(fields=['source', 'destination'], name='core_triphi_source__3f374d_idx'), models.Index(fields=['traffic_level'], name='core_triphi_traffic_db2c65_idx'), models.Index(fields=['weather_condition'], name='core_triphi_weather_a7bf61_idx'), models.Index(fields=['-date_of_travel'], name='core_triphi_date_of_98259c_idx')],
            },
        ),
    ]
