# Generated by Django 5.0.1 on 2026-02-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('participants', models.TextField(help_text='Comma-separated list of participants')),
                ('transcript', models.TextField(blank=True, help_text='Meeting transcript or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(help_text='Positive, Neutral, or Negative', max_length=20)),
                ('sentiment_score', models.FloatField(help_text='Score from -1 (negative) to 1 (positive)')),
                ('productivity_score', models.FloatField(help_text='Score from 0 to 100')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('action_items_extracted', models.PositiveIntegerField(default=0)),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('follow_up_recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('meetings_covered', models.ManyToManyField(to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Report',
                'verbose_name_plural': 'Meeting Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
