# Generated by Django 5.2 on 2026-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=50)),
                ('points_required', models.IntegerField(default=0, help_text='Points needed to earn this badge')),
                ('sessions_required', models.IntegerField(default=0, help_text='Completed sessions needed to earn this badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_required', 'sessions_required'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.badge'),
        ),
    ]
