# Generated by Django 6.0.1 on 2026-01-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject or title of the exam', max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration of the exam in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when exam was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=200)),
                ('student_id', models.CharField(help_text='Unique student identifier', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProctorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the violation was detected')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_paste', 'Copy/Paste Detected'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('phone_detected', 'Phone Detected'), ('suspicious_object', 'Suspicious Object'), ('no_movement', 'No Movement (Long Period)'), ('other', 'Other Violation')], help_text='Type of violation detected', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the violation', null=True)),
                ('exam', models.ForeignKey(help_text='Exam during which the violation occurred', on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='monitoring.exam')),
                ('student', models.ForeignKey(help_text='Student who committed the violation', on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='monitoring.student')),
            ],
            options={
                'verbose_name': 'Proctor Log',
                'verbose_name_plural': 'Proctor Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
