# Generated by Django 5.2 on 2026-01-29 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.CharField(blank=True, help_text='Admin/instructor who created the exam', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Exam instructions for students'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=40, help_text='Minimum passing score percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proctorlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the exam session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the exam session ended', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('terminated', 'Terminated'), ('auto_submitted', 'Auto Submitted')], default='in_progress', help_text='Current status of the exam session', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of student', null=True)),
                ('browser_info', models.TextField(blank=True, help_text='Browser user agent string')),
                ('violation_count', models.PositiveIntegerField(default=0, help_text='Total violations during session')),
                ('screenshot_captured', models.BooleanField(default=False, help_text='Whether screenshots were captured')),
                ('exam', models.ForeignKey(help_text='Exam being taken', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='monitoring.exam')),
                ('student', models.ForeignKey(help_text='Student taking the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='monitoring.student')),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score achieved as percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending Review')], help_text='Pass/Fail status', max_length=20)),
                ('answers', models.JSONField(default=dict, help_text="Student's answers stored as JSON")),
                ('integrity_score', models.PositiveIntegerField(default=100, help_text='Integrity score from proctoring (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Risk score based on violations')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the result was generated')),
                ('exam', models.ForeignKey(help_text='Exam that was taken', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.exam')),
                ('student', models.ForeignKey(help_text='Student who took the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='monitoring.student')),
                ('session', models.OneToOneField(help_text='The exam session this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='monitoring.examsession')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of question in exam')),
                ('exam', models.ForeignKey(help_text='Exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='monitoring.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='The choice text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is the correct answer')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of choice')),
                ('question', models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='monitoring.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['question', 'order'],
            },
        ),
    ]
