# Generated by Django 5.0.1 on 2026-02-06 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('transaction_created', 'Transaction Created'), ('fraud_detected', 'Fraud Detected'), ('alert_created', 'Alert Created'), ('model_trained', 'Model Trained'), ('report_generated', 'Report Generated'), ('investigation_started', 'Investigation Started'), ('investigation_closed', 'Investigation Closed')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('true_positives', models.IntegerField(default=0)),
                ('true_negatives', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('training_samples', models.IntegerField(default=0)),
                ('test_samples', models.IntegerField(default=0)),
                ('fraud_samples', models.IntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Metrics',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('deposit', 'Deposit'), ('payment', 'Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('merchant', models.CharField(max_length=200)),
                ('merchant_category', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('card_number_last4', models.CharField(max_length=4)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fraud', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('fraud_reason', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('browser', models.CharField(blank=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='transaction_timesta_688061_idx'), models.Index(fields=['is_fraud', '-timestamp'], name='transaction_is_frau_b9b4c6_idx'), models.Index(fields=['risk_score'], name='transaction_risk_sc_14f8bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed Fraud'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('description', models.TextField()),
                ('risk_score', models.FloatField()),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='transaction_status_faa3af_idx')],
            },
        ),
    ]
