# Generated by Django 6.0.2 on 2026-02-09 09:31

import django.db.models.deletion
import django.utils.timezone
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_documents', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'System Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File')], max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='ML classification confidence score (0-1)', null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False, help_text='Whether text extraction is complete')),
                ('view_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('search_result', 'Search Result')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['query'], name='documents_s_query_daccbe_idx'), models.Index(fields=['executed_at'], name='documents_s_execute_4d11e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_fec314_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='documents_d_file_ty_1bb410_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_date'], name='documents_d_upload__301055_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['document'], name='documents_d_documen_0260e2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccess',
            index=models.Index(fields=['accessed_at'], name='documents_d_accesse_c0202e_idx'),
        ),
    ]
