# Generated by Django 5.0.1 on 2026-02-13 07:46

import django.core.validators
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('camera_id', models.CharField(help_text='Unique camera identifier', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('WEBCAM', 'Webcam'), ('IP_CAMERA', 'IP Camera'), ('VIDEO_FILE', 'Video File'), ('RTSP_STREAM', 'RTSP Stream')], default='WEBCAM', max_length=20)),
                ('source_path', models.CharField(help_text='Camera index (for webcam) or URL/path (for IP camera/video file)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('resolution_width', models.IntegerField(default=640)),
                ('resolution_height', models.IntegerField(default=480)),
                ('fps', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Camera Configuration',
                'verbose_name_plural': 'Camera Configurations',
            },
        ),
        migrations.CreateModel(
            name='RestrictedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restricted zone', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of why this zone is restricted')),
                ('x1', models.IntegerField(help_text='Top-left X coordinate')),
                ('y1', models.IntegerField(help_text='Top-left Y coordinate')),
                ('x2', models.IntegerField(help_text='Bottom-right X coordinate')),
                ('y2', models.IntegerField(help_text='Bottom-right Y coordinate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restricted Zone',
                'verbose_name_plural': 'Restricted Zones',
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('workers_detected', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('safety_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('active_cameras', models.IntegerField(default=1)),
                ('monitoring_hours', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the violation was detected')),
                ('camera_id', models.CharField(default='CAM-01', help_text='Identifier for the camera that detected the incident', max_length=50)),
                ('hazard_type', models.CharField(choices=[('NO_HELMET', 'No Helmet'), ('NO_VEST', 'No Safety Vest'), ('RESTRICTED_ZONE', 'Restricted Zone Intrusion'), ('NO_PPE', 'Missing PPE'), ('MULTIPLE_VIOLATIONS', 'Multiple Violations')], help_text='Type of safety violation detected', max_length=50)),
                ('confidence_score', models.FloatField(help_text='AI detection confidence score (0-100%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image_path', models.ImageField(blank=True, help_text='Snapshot image captured at the time of violation', null=True, upload_to=monitoring.models.snapshot_upload_path)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the incident has been reviewed and resolved')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the incident', null=True)),
                ('detection_details', models.JSONField(blank=True, default=dict, help_text='Additional detection metadata (bounding boxes, etc.)')),
            ],
            options={
                'verbose_name': 'Safety Incident',
                'verbose_name_plural': 'Safety Incidents',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_3e19ac_idx'), models.Index(fields=['hazard_type'], name='monitoring__hazard__80d899_idx'), models.Index(fields=['is_resolved'], name='monitoring__is_reso_36cd8b_idx')],
            },
        ),
    ]
