# Generated by Django 5.0.1 on 2026-02-14 05:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name (e.g., Mathematics)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Subject code (e.g., MATH101)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subject', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='User role: Student or Teacher', max_length=10)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exam title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Exam description or instructions', null=True)),
                ('total_marks', models.IntegerField(help_text='Total marks for the exam', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.IntegerField(help_text='Duration of exam in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_marks', models.IntegerField(help_text='Minimum marks required to pass', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', help_text='Exam status', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, help_text='When exam becomes available', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When exam closes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created the exam', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject of the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='examination_app.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name (e.g., Algebra, Geometry)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the topic', null=True)),
                ('chapter_number', models.IntegerField(default=1, help_text='Chapter or topic order number', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='examination_app.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['subject', 'chapter_number'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('true_false', 'True/False')], default='mcq', help_text='Type of question', max_length=10)),
                ('text', models.TextField(help_text='Question text')),
                ('option_a', models.CharField(blank=True, help_text='Option A', max_length=500)),
                ('option_b', models.CharField(blank=True, help_text='Option B', max_length=500)),
                ('option_c', models.CharField(blank=True, help_text='Option C', max_length=500, null=True)),
                ('option_d', models.CharField(blank=True, help_text='Option D', max_length=500, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('True', 'True'), ('False', 'False')], help_text='Correct answer', max_length=5)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks for this question', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('question_number', models.IntegerField(help_text='Question order in exam', validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='Exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examination_app.exam')),
                ('topic', models.ForeignKey(help_text='Topic this question relates to (for analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='examination_app.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam', 'question_number'],
                'unique_together': {('exam', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When student started the exam')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('current_question', models.IntegerField(default=1, help_text='Current question number')),
                ('answers_json', models.JSONField(default=dict, help_text='Temporary storage of answers before submission')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether exam has been completed')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='examination_app.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Progress',
                'verbose_name_plural': 'Exam Progress Records',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Total marks obtained', max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage score', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_questions', models.IntegerField(help_text='Total number of questions')),
                ('correct_answers', models.IntegerField(help_text='Number of correct answers')),
                ('wrong_answers', models.IntegerField(help_text='Number of wrong answers')),
                ('time_taken_minutes', models.IntegerField(help_text='Total time taken to complete exam (in minutes)')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], help_text='Exam result status', max_length=20)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when exam was completed')),
                ('exam', models.ForeignKey(help_text='Exam that was taken', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination_app.exam')),
                ('student', models.ForeignKey(help_text='Student who took the exam', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(help_text='Answer selected by student', max_length=5)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, help_text='Marks obtained for this question', max_digits=5)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer this question (in seconds)', null=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when answer was submitted')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='examination_app.question')),
                ('student', models.ForeignKey(help_text='Student who answered', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['answered_at'],
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_topics', models.JSONField(default=dict, help_text='JSON object containing weak topics with accuracy percentages')),
                ('strong_topics', models.JSONField(default=dict, help_text='JSON object containing strong topics with accuracy percentages')),
                ('overall_accuracy', models.DecimalField(decimal_places=2, default=0, help_text='Overall accuracy percentage in this subject', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_attempts', models.IntegerField(default=0, help_text='Total number of questions attempted in this subject')),
                ('avg_time_per_question', models.DecimalField(blank=True, decimal_places=2, help_text='Average time taken per question (in seconds)', max_digits=6, null=True)),
                ('suggestions', models.TextField(help_text='AI-generated textual suggestions for improvement')),
                ('detailed_insights', models.JSONField(blank=True, default=dict, help_text='Detailed insights about performance (topic-wise breakdown, trends, etc.)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of last analysis update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when first analysis was created')),
                ('student', models.ForeignKey(help_text='Student being analyzed', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_analyses', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='performance_analyses', to='examination_app.subject')),
            ],
            options={
                'verbose_name': 'Performance Analysis',
                'verbose_name_plural': 'Performance Analyses',
                'ordering': ['-last_updated'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
