# Generated by Django 5.0.1 on 2026-02-10 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food & Beverages'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('books', 'Books & Media'), ('other', 'Other')], default='other', max_length=20)),
                ('current_stock', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_demand', models.IntegerField()),
                ('recommended_stock', models.IntegerField()),
                ('date_of_prediction', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('low_stock', 'Low Stock'), ('optimal', 'Optimal'), ('overstock', 'Overstock')], default='optimal', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('prediction_period', models.CharField(default='Next 30 days', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory_system.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Predictions',
                'ordering': ['-date_of_prediction'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='inventory_system.product')),
            ],
            options={
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-sale_date'],
            },
        ),
    ]
