# Generated by Django 5.2 on 2026-02-06 05:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('license_type', models.CharField(choices=[('class_a', 'Class A (CDL)'), ('class_b', 'Class B (CDL)'), ('class_c', 'Class C'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], max_length=20, verbose_name='License Type')),
                ('license_expiry', models.DateField(verbose_name='License Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Hire Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('other', 'Other')], max_length=20, verbose_name='Vehicle Type')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('current_mileage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Mileage')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('fuel_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fuel Capacity (gallons)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date/Time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date/Time')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance (miles)')),
                ('fuel_used', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fuel Used (gallons)')),
                ('start_location', models.CharField(max_length=200, verbose_name='Start Location')),
                ('end_location', models.CharField(max_length=200, verbose_name='End Location')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Trip Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Maintenance Date/Time')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('emergency', 'Emergency Repair'), ('preventive', 'Preventive Maintenance')], max_length=20, verbose_name='Maintenance Type')),
                ('mileage_at_service', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mileage at Service')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost ($)')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Severity')),
                ('performed_by', models.CharField(max_length=200, verbose_name='Performed By')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Parts Replaced')),
                ('next_maintenance_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Next Maintenance Mileage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('maintenance_due', 'Maintenance Due'), ('maintenance_overdue', 'Maintenance Overdue'), ('low_efficiency', 'Low Efficiency'), ('high_mileage', 'High Mileage'), ('license_expiry', 'License Expiring'), ('safety', 'Safety Concern'), ('other', 'Other')], max_length=30, verbose_name='Alert Type')),
                ('message', models.TextField(verbose_name='Alert Message')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='info', max_length=20, verbose_name='Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
