# Generated by Django 6.0.1 on 2026-01-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cereals', 'Cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('legumes', 'Legumes'), ('tubers', 'Tubers'), ('cash_crops', 'Cash Crops')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in days')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('months', models.CharField(help_text="Comma-separated months, e.g., 'June, July, August'", max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, help_text='pH level (0-14)', max_digits=4)),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Moisture percentage', max_digits=5)),
                ('type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=20)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='YieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Yield quantity in tons/hectare', max_digits=10)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_records', to='agriSense.crop')),
            ],
            options={
                'verbose_name': 'Yield Record',
                'verbose_name_plural': 'Yield Records',
                'ordering': ['-year', '-recorded_date'],
            },
        ),
    ]
