# Generated by Django 6.0.1 on 2026-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriSense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='suitable_seasons',
            field=models.ManyToManyField(blank=True, help_text='Seasons when this crop can be grown', related_name='crops', to='agriSense.season'),
        ),
        migrations.AddField(
            model_name='crop',
            name='suitable_soil_types',
            field=models.JSONField(blank=True, default=list, help_text="List of suitable soil types (e.g., ['clay', 'loamy'])"),
        ),
    ]
