# Generated by Django 5.0.1 on 2026-02-06 11:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Income ($)')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=20, verbose_name='Employment Status')),
                ('years_employed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Years Employed')),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Debt-to-Income Ratio (%)')),
                ('risk_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Risk Probability (0-1)')),
                ('risk_category', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20, null=True, verbose_name='Risk Category')),
                ('eligibility_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('manual_review', 'Manual Review'), ('rejected', 'Rejected')], max_length=20, null=True, verbose_name='Eligibility Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)], verbose_name='Credit Score (300-850)')),
                ('num_open_loans', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Open Loans')),
                ('num_credit_lines', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Credit Lines')),
                ('late_payments', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Late Payments (Last 2 Years)')),
                ('bankruptcies', models.BooleanField(default=False, verbose_name='History of Bankruptcy')),
                ('home_ownership_status', models.CharField(choices=[('rent', 'Rent'), ('mortgage', 'Mortgage'), ('own', 'Own Outright'), ('other', 'Other')], max_length=20, verbose_name='Home Ownership Status')),
                ('total_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Credit Limit ($)')),
                ('credit_utilization', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Credit Utilization (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='assessment.applicant', verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Financial Data',
                'verbose_name_plural': 'Financial Data Records',
            },
        ),
    ]
