# Generated by Django 5.0.1 on 2026-02-11 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=200)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lng', models.FloatField(blank=True, null=True)),
                ('estimated_distance', models.FloatField(help_text='Distance in miles')),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('battery_consumption', models.FloatField(help_text='Estimated battery consumption in kWh')),
                ('initial_battery_percent', models.IntegerField(help_text='Starting battery percentage')),
                ('final_battery_percent', models.IntegerField(help_text='Expected final battery percentage')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField(help_text='Order of this stop in the trip')),
                ('estimated_charge_time', models.IntegerField(help_text='Estimated charging time in minutes')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated charging cost', max_digits=6)),
                ('battery_before_charge', models.IntegerField(help_text='Battery % before charging')),
                ('battery_after_charge', models.IntegerField(help_text='Battery % after charging')),
                ('notes', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargingstation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stops', to='planner.trip')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
