# Generated by Django 5.0.1 on 2026-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimated_distance',
            field=models.FloatField(help_text='Distance in kilometers'),
        ),
    ]
