# Generated by Django 4.2 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=200)),
                ('age', models.IntegerField(help_text='Age in years (minimum 18)', validators=[django.core.validators.MinValueValidator(18)])),
                ('annual_income', models.DecimalField(decimal_places=2, help_text='Annual income in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], default='employed', max_length=20)),
                ('income_stability', models.CharField(choices=[('very_stable', 'Very Stable - Government/Large Corporate'), ('stable', 'Stable - Regular Employment'), ('somewhat_stable', 'Somewhat Stable - Commission Based'), ('unstable', 'Unstable - Freelance/Gig Economy')], default='stable', max_length=20)),
                ('dependents', models.IntegerField(default=0, help_text='Number of financial dependents', validators=[django.core.validators.MinValueValidator(0)])),
                ('investment_experience_years', models.IntegerField(default=0, help_text='Years of investment experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date')),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance Income'), ('investment', 'Investment Returns'), ('business', 'Business Income'), ('other_income', 'Other Income'), ('housing', 'Housing - Rent/Mortgage'), ('food', 'Food & Groceries'), ('utilities', 'Utilities - Electricity, Water, Gas'), ('healthcare', 'Healthcare & Insurance'), ('transportation', 'Transportation'), ('education', 'Education'), ('dining', 'Dining Out'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('subscriptions', 'Subscriptions'), ('other_expense', 'Other Expense')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(help_text='Risk tolerance score from 0 (very conservative) to 100 (very aggressive)')),
                ('classification', models.CharField(choices=[('conservative', 'Conservative - Low Risk'), ('moderate', 'Moderate - Balanced Risk'), ('aggressive', 'Aggressive - High Risk')], max_length=20)),
                ('age_factor_score', models.IntegerField(help_text='Score based on age (0-100)')),
                ('savings_rate_score', models.IntegerField(help_text='Score based on savings rate (0-100)')),
                ('income_stability_score', models.IntegerField(help_text='Score based on income stability (0-100)')),
                ('experience_score', models.IntegerField(help_text='Score based on investment experience (0-100)')),
                ('savings_rate', models.DecimalField(decimal_places=2, help_text='Savings rate as percentage', max_digits=5)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('essential_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discretionary_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spending_pattern', models.CharField(help_text="Categorized spending pattern", max_length=50)),
                ('insights', models.TextField(help_text='AI-generated financial insights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Risk Profile',
                'verbose_name_plural': 'Risk Profiles',
            },
        ),
    ]
