# Generated by Django 5.0.1 on 2026-02-14 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(help_text='Date of Birth')),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Classes'), ('SC', 'Scheduled Castes'), ('ST', 'Scheduled Tribes'), ('EWS', 'Economically Weaker Section'), ('PWD', 'Persons with Disabilities')], default='GEN', max_length=5)),
                ('highest_qualification', models.CharField(choices=[('10TH', '10th / Matriculation'), ('12TH', '12th / Intermediate'), ('DIPLOMA', 'Diploma'), ('GRADUATE', 'Graduate'), ('POST_GRADUATE', 'Post Graduate'), ('PHD', 'Doctorate (PhD)'), ('OTHER', 'Other')], default='GRADUATE', help_text='Highest educational qualification', max_length=20)),
                ('state', models.CharField(blank=True, help_text='State of residence', max_length=100, null=True)),
                ('preferred_exam_types', models.CharField(blank=True, help_text='Comma separated exam types (UPSC, SSC, BANKING, etc.)', max_length=255, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
