# Generated by Django 5.0.1 on 2026-02-09 08:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business process', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the process')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_cycle_time', models.FloatField(blank=True, help_text='Target cycle time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Business Process',
                'verbose_name_plural': 'Business Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the process step', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the step')),
                ('step_order', models.PositiveIntegerField(help_text='Order of execution in the workflow', validators=[django.core.validators.MinValueValidator(1)])),
                ('step_type', models.CharField(choices=[('manual', 'Manual Task'), ('automated', 'Automated Task'), ('approval', 'Approval Gate'), ('notification', 'Notification'), ('integration', 'System Integration')], default='manual', max_length=20)),
                ('estimated_duration', models.FloatField(blank=True, help_text='Estimated duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(help_text='Parent business process', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.businessprocess')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['process', 'step_order'],
                'unique_together': {('process', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cycle_time', 'Average Cycle Time'), ('throughput', 'Throughput'), ('efficiency', 'Efficiency Score'), ('quality', 'Quality Score'), ('bottleneck_score', 'Bottleneck Score')], max_length=20)),
                ('value', models.FloatField(help_text='Metric value')),
                ('date', models.DateField(help_text='Date of metric calculation')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.businessprocess')),
            ],
            options={
                'verbose_name': 'Process Metric',
                'verbose_name_plural': 'Process Metrics',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('process', 'metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OperationalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='Unique identifier for this execution run', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('assigned_to', models.CharField(blank=True, help_text='Person or system assigned', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(help_text='Associated business process', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.businessprocess')),
                ('step', models.ForeignKey(blank=True, help_text='Associated process step (null for process-level logs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.processstep')),
            ],
            options={
                'verbose_name': 'Operational Data',
                'verbose_name_plural': 'Operational Data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run_id'], name='core_operat_run_id_cb50aa_idx'), models.Index(fields=['status'], name='core_operat_status_c58ed6_idx'), models.Index(fields=['process', 'step'], name='core_operat_process_5cf4e2_idx'), models.Index(fields=['created_at'], name='core_operat_created_ebe397_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the recommendation', max_length=300)),
                ('category', models.CharField(choices=[('bottleneck', 'Bottleneck Removal'), ('automation', 'Automation Opportunity'), ('resource', 'Resource Allocation'), ('process', 'Process Redesign'), ('performance', 'Performance Improvement')], default='performance', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('recommendation', models.TextField(help_text='Specific recommendation for improvement')),
                ('current_value', models.FloatField(blank=True, help_text='Current metric value', null=True)),
                ('target_value', models.FloatField(blank=True, help_text='Target metric value', null=True)),
                ('potential_savings', models.FloatField(blank=True, help_text='Potential time savings in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('impact_score', models.FloatField(default=0, help_text='Impact score (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Raw analysis data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(help_text='Process this recommendation applies to', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.businessprocess')),
                ('step', models.ForeignKey(blank=True, help_text='Step this recommendation applies to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.processstep')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-impact_score', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_recomm_status_e131d2_idx'), models.Index(fields=['priority'], name='core_recomm_priorit_ab2b06_idx'), models.Index(fields=['category'], name='core_recomm_categor_1cc17b_idx')],
            },
        ),
    ]
