# Generated by Django 5.2 on 2026-02-05 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_routes_calculated', models.IntegerField(default=0)),
                ('avg_optimization_time_ms', models.FloatField(default=0.0)),
                ('avg_savings_minutes', models.FloatField(default=0.0)),
                ('avg_cost_savings_usd', models.FloatField(default=0.0)),
                ('traffic_prediction_accuracy', models.FloatField(default=0.0)),
                ('daily_stats', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Optimization Metrics',
                'verbose_name_plural': 'Optimization Metrics',
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(max_length=255, unique=True)),
                ('traffic_level', models.FloatField(default=1.0)),
                ('avg_speed', models.FloatField(default=60.0)),
                ('hour', models.IntegerField(default=12)),
                ('day_of_week', models.IntegerField(default=1)),
                ('historical_congestion', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('fastest', 'Fastest'), ('shortest', 'Shortest'), ('scenic', 'Most Scenic'), ('eco', 'Eco-Friendly')], default='fastest', max_length=20)),
                ('distance_km', models.FloatField()),
                ('estimated_time_minutes', models.IntegerField()),
                ('path_coordinates', models.JSONField(default=list)),
                ('traffic_factor', models.FloatField(default=1.0)),
                ('fuel_cost_estimate', models.FloatField(default=0.0)),
                ('co2_emission_kg', models.FloatField(default=0.0)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='route_planner.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='route_planner.location')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['is_recommended', 'estimated_time_minutes'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('selected_route_type', models.CharField(max_length=20)),
                ('distance_km', models.FloatField()),
                ('estimated_time_minutes', models.IntegerField()),
                ('fuel_cost', models.FloatField(default=0.0)),
                ('available_routes', models.JSONField(default=dict)),
                ('optimization_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route History',
                'verbose_name_plural': 'Route History',
                'ordering': ['-created_at'],
            },
        ),
    ]
