# Generated by Django 5.2 on 2026-01-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('group', models.CharField(choices=[('COMPANY', 'Company'), ('PRODUCTS', 'Products'), ('RESOURCES', 'Resources'), ('LEGAL', 'Legal'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Footer Links',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, max_length=255)),
                ('custom_breadcrumbs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumb', to='pages.page')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumbs',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Navigations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link_type', models.CharField(choices=[('INTERNAL', 'Internal Link'), ('EXTERNAL', 'External Link'), ('PAGE', 'Page Link'), ('ANCHOR', 'Anchor Link')], default='INTERNAL', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('target', models.CharField(choices=[('_SELF', 'Same Window'), ('_BLANK', 'New Window'), ('_PARENT', 'Parent Window'), ('_TOP', 'Top Window')], default='_SELF', max_length=10)),
                ('css_classes', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.navigation')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navigationitem')),
            ],
            options={
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order'],
            },
        ),
    ]
