# Generated by Django 5.0.1 on 2026-02-13 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='Date and time of traffic recording')),
                ('location', models.CharField(choices=[('Main Street Junction', 'Main Street Junction'), ('Highway Exit 45', 'Highway Exit 45'), ('City Center Square', 'City Center Square'), ('North Avenue Bridge', 'North Avenue Bridge'), ('Market Street Crossing', 'Market Street Crossing'), ('Railway Road Intersection', 'Railway Road Intersection'), ('University Gate', 'University Gate'), ('Hospital District', 'Hospital District'), ('Industrial Area', 'Industrial Area'), ('Suburb Entrance', 'Suburb Entrance')], help_text='Location of the traffic recording', max_length=100)),
                ('vehicle_count', models.IntegerField(help_text='Number of vehicles passed', validators=[django.core.validators.MinValueValidator(0)])),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Cloudy', 'Cloudy'), ('Foggy', 'Foggy')], help_text='Weather condition during recording', max_length=20)),
                ('congestion_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], help_text='Predicted/Labeled congestion level', max_length=10)),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data Records',
                'ordering': ['-date_time'],
            },
        ),
    ]
