# Generated by Django 5.0.1 on 2026-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact name', max_length=100)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('message', models.TextField(help_text='Contact message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Message timestamp')),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.IntegerField(help_text='Nitrogen level (N)')),
                ('phosphorus', models.IntegerField(help_text='Phosphorus level (P)')),
                ('potassium', models.IntegerField(help_text='Potassium level (K)')),
                ('ph_level', models.FloatField(help_text='Soil pH level')),
                ('moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('recommended_crop', models.CharField(help_text='AI recommended crop', max_length=100)),
                ('fertilizer_suggestion', models.TextField(help_text='Fertilizer recommendations')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Analysis timestamp')),
            ],
            options={
                'verbose_name': 'Soil Data',
                'verbose_name_plural': 'Soil Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
