# Generated by Django 5.0.1 on 2026-02-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('connector_type', models.CharField(choices=[('J1772', 'J1772 (Level 2)'), ('CCS', 'CCS Combo (Level 3)'), ('CHAdeMO', 'CHAdeMO (Level 3)'), ('Tesla', 'Tesla Supercharger'), ('NEMA', 'NEMA 5-15 (Level 1)')], max_length=20)),
                ('power_kw', models.FloatField(help_text='Charging power in kW')),
                ('price_per_kwh', models.DecimalField(decimal_places=3, default=0.15, max_digits=5)),
                ('fast_charging', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('total_ports', models.IntegerField(default=2)),
                ('available_ports', models.IntegerField(default=2)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities (WiFi, Restroom, etc.)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('ev_type', models.CharField(choices=[('BEV', 'Battery Electric Vehicle'), ('PHEV', 'Plug-in Hybrid Electric Vehicle')], default='BEV', max_length=4)),
                ('battery_capacity', models.FloatField(help_text='Battery capacity in kWh')),
                ('range_miles', models.IntegerField(help_text='Estimated range in miles')),
                ('charging_speed', models.FloatField(default=50, help_text='Max charging speed in kW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
