# Generated by Django 5.0.1 on 2026-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='range_miles',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='range_km',
            field=models.IntegerField(default=300, help_text='Estimated range in kilometers'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='connector_type',
            field=models.CharField(choices=[('Type2', 'Type 2 (AC)'), ('CCS2', 'CCS Combo 2 (DC Fast)'), ('CHAdeMO', 'CHAdeMO (DC Fast)'), ('Bharat_DC', 'Bharat DC DC-001 (India Standard)'), ('Tesla', 'Tesla Supercharger'), ('GB_T', 'GB/T (Chinese Standard)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='price_per_kwh',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
