# Generated by Django 5.0.1 on 2026-02-13 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Street address or landmark', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('incident_type', models.CharField(choices=[('pothole', 'Pothole'), ('drainage', 'Drainage'), ('streetlight', 'Streetlight'), ('footpath', 'Footpath'), ('other', 'Other')], default='other', help_text='Auto-categorized by AI, can be overridden', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Supporting image evidence', null=True, upload_to='incident_images/%Y/%m/')),
                ('latitude', models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True)),
                ('severity_score', models.IntegerField(default=30, help_text='AI-calculated risk score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('authority_notes', models.TextField(blank=True, help_text='Notes from authority review', null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(help_text='Name of the victim/claimant', max_length=255)),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Claim amount in local currency', max_digits=10)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='filed', max_length=20)),
                ('evidence_description', models.TextField(help_text='Detailed evidence and justification for the claim')),
                ('filed_date', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True, help_text='Authority review notes', null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final approved amount if different from claimed', max_digits=10, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Authority user who reviewed the claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(limit_choices_to={'status': 'verified'}, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='reports.incident')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-filed_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority')], default='citizen', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-timestamp'], name='reports_inc_status_6f582c_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['location'], name='reports_inc_locatio_608cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity_score'], name='reports_inc_severit_e28300_idx'),
        ),
    ]
